### ISSUE TITLE
Fresh install fails to start

### ISSUE THREAD

**Issue by dsbert** [vuetifyjs/webpack-ssr#3]
After performing the following operations, the dev environment fails to start and I am presented with an error.

```bash
vue init vuetifyjs/webpack-ssr
yarn
npm start dev
```

The error

```bash
Error: ENOENT: no such file or directory, open 'C:\client2\dist\server-bundle.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\client2\server.js:19:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by dsbert** [comment]
I just realized I typed the wrong command. I should have used `npm run dev`.
